export const REGISTER_CLIENT = "REGISTER_CLIENT";
export const SET_WEBSOCKET_URL = "SET_WEBSOCKET_URL";
export const WEBSOCKET_OPEN = "WEBSOCKET_OPEN";
export const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE";
export const WEBSOCKET_ERROR = "WEBSOCKET_ERROR";
export const WEBSOCKET_CLOSE = "WEBSOCKET_CLOSE";
export const SEND_WEBSOCKET_MESSAGE = "SEND_WEBSOCKET_MESSAGE";
